### ISSUE TITLE
PermissionsManager.removePendingAction is never called.

### ISSUE THREAD

**Issue by alexanderbliznyuk** [anthonycr/Grant#1]
According to java doc it should be called internally. It will lead to memory leaks if you create annonymous PermissionsResultAction in Activity class.

**Comment by anthonycr** [comment]
I should remove this method from the PermissionsManager, the removal is currently being done manually using `iterator.remove()` from within the `notifyPermissionsChange` method. I originally intended to use the removePendingAction method, but you can't call list.remove while looping through it, so I switched to using iterators.

**Comment by anthonycr** [comment]
Fixed in https://github.com/anthonycr/Grant/commit/00a6cbccb58543ee14a4a8d25772ba4e0fbf83be
