### ISSUE TITLE
hasAllPermissions

### ISSUE THREAD

**Issue by QuickBrownFoxy** [anthonycr/Grant#10]
Shouldn't PermissionsManager.hasPermission method condsider the fix you have made about old versions of Android ? Change log was : Fixed bug where new permissions requested on old Android versions were denied (optional method can change this).

**Comment by anthonycr** [comment]
Yes I will fix this - missed that method.

**Comment by anthonycr** [comment]
Fixed: https://github.com/anthonycr/Grant/releases/tag/v1.1.2
