### ISSUE TITLE
How can we test android permission?

### ISSUE THREAD

**Issue by Tony---Zhang** [anthonycr/Grant#6]
1. Why PermissionsManager class use `final`. In my point of view, I think no class will inherit the Manager class. If they inherit it, the developer have the duty to make sure his/her inherited class can work in right way.
   Another reason is that:
   We can not test it(Mock it).

Reference:
https://github.com/anthonycr/Grant/pull/7
1. Before android M, why we test android device has the permission or not?

**Comment by anthonycr** [comment]
You have a good point, the only reason for making the permissions manager final was to indicate that it should not be overridden. I guess a better way would be just to not make it final and to add documentation that extending the class likely is not a good idea. I'll merge your PR, thanks.

**Comment by Tony---Zhang** [comment]
:+1:
