### ISSUE TITLE
Multiple permission request with requestPermissionsIfNecessaryForResult

### ISSUE THREAD

**Issue by QuickBrownFoxy** [anthonycr/Grant#8]
I only get one onDenied result if I pass permission requests from different groups.

**Comment by anthonycr** [comment]
I'll look into this, this may be related to a recent PR where I was forgetting to remove a permissions action: https://github.com/anthonycr/Grant/pull/4

**Comment by anthonycr** [comment]
Fixed in https://github.com/anthonycr/Grant/releases/tag/v1.1.1
